version: '3.8'

services:
  bot:
    image: filipkof/telegram-bot:latest
    container_name: telegram_bot
    restart: always
    depends_on:
      - selenoid
    environment:
      - SELENOID_URL=http://selenoid:4444/wd/hub
    ports:
      - "8080:8080"

  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Позволяет Selenoid запускать браузеры
      - "./config:/etc/selenoid/"  # Конфигурация браузеров
    command: ["-conf", "/etc/selenoid/browsers.json"]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui
    container_name: selenoid_ui
    restart: always
    depends_on:
      - selenoid
    ports:
      - "8081:8080"