version: "3"
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aerokube/selenoid:/etc/selenoid
    command: ["-limit", "10"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    ports:
      - "8080:8080"
    links:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

  telegram-bot:
    image: filipkof/downloader-bot:latest
    ports:
      - "8080:8080"
    depends_on:
      - selenoid